require: rubocop-performance

AllCops:
  Exclude:
    - bin/*
    - db/migrate/*
    - db/schema.rb
    - db/seeds.rb
    - lib/*/Gemfile
    - lib/*/Rakefile
    - lib/*/bin/*
    - lib/*/*.gemspec
    - node_modules/**/*
    - spec/**/*
    - tmp/**/*

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 1000

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Enabled: false
  Max: 120

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Max: 1000

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 20

Performance/Casecmp:
  Enabled: false

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SafeNavigation:
  ConvertTry: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - simulation
    - staging
    - production

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MethodDefParentheses:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/RescueModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: true

Style/SingleLineMethods:
  Enabled: false

Style/SymbolArray:
  Enabled: false
