language: ruby
bundler_args: --without deployment
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - cd ext && bundle exec ruby extconf.rb && make
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: doc
  on:
    branch: master
